### ISSUE TITLE
Support Request

### ISSUE THREAD

**Issue by kontinyu** [ivkos/PushBullet-for-PHP#51]
Hello,
Can you please give an example with try /catch error handling. Cant seem to get it work !

**Comment by dgadelha** [comment]
Hi

You can simply do that before everything:

```
<?php

function HandleError($ErrNo, $ErrStr, $ErrFile = null, $ErrLine = null, $ErrContext = [], $Exception = false) {
    if (!(error_reporting() & $ErrNo) and !$Exception) {
        return;
    }

    echo "[#{$ErrNo}] {$ErrStr} at {$ErrFile} on line {$ErrLine}.", PHP_EOL;
    return true;
}

function HandleException($Exception) {
    HandleError($Exception->getCode() ? $Exception->getCode() : E_USER_ERROR, $Exception->getMessage(), $Exception->getFile(), $Exception->getLine(), $Exception->getTrace(), true);
    return true;
}

error_reporting(E_ALL & ~E_NOTICE);
set_error_handler("HandleError");
set_exception_handler("HandleException");

// Your code here
```

This will handle both exceptions and user errors, anywhere.

Otherwise, just surround the code you want with simple try and catch code:

```
<?php

try {
    // your code here
} catch (Exception $Exception) {
   echo "[#" . ($Exception->getCode() ? $Exception->getCode() : E_USER_ERROR) . "] " . $Exception->getMessage() . " at " . $Exception->getFile() . " on line " . $Exception->getLine() . PHP_EOL;
}
```

I suggest you to read the [Error Handling and Logging](http://php.net/manual/en/book.errorfunc.php) at the PHP manual, also take a look at the [Errors](http://php.net/manual/en/language.errors.php) and [Exceptions](http://php.net/manual/en/language.exceptions.php) language references.

**Comment by kontinyu** [comment]
Oh you are a godsend.
THANK YOU VERY MUCH! I appreciate the work you do.
